import Submission from '../models/Submission.js';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// @desc    Get submissions
// @route   GET /api/submissions
// @access  Private
const getSubmissions = async (req, res) => {
  try {
    const { taskId } = req.query;
    let query = {};

    // Ensure taskId is filtered if provided by the dashboard
    if (taskId) query.taskId = taskId;

    // Students only see their own work; Instructors see everyone's
    if (req.user.role === 'STUDENT') {
        query.studentId = req.user.id;
    }

    // IMPORTANT: .populate links the studentId to the actual User data
    const submissions = await Submission.find(query)
        .populate('studentId', 'name email') 
        .sort({ submittedAt: -1 });
    
    res.status(200).json({ success: true, data: submissions });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Create/Update submission
// @route   POST /api/submissions
// @access  Private (Student)
const createSubmission = async (req, res) => {
  try {
    console.log("---------------------------------------------------------");
    console.log("[Submission] Create Request Received");
    console.log("[Submission] File:", req.file ? req.file.filename : 'No file');

    const { taskId, studentName, code, language, output } = req.body; 
    const studentId = req.user.id;
    
    // File handling (Local Storage Strategy)
    let fileUrl = '';
    let originalFileName = '';
    let fileSize = 0;
    let fileType = '';

    if (req.file) {
        // Use the filename generated by multer (saved in uploads/)
        fileUrl = req.file.filename;
        originalFileName = req.file.originalname;
        fileSize = req.file.size;
        fileType = req.file.mimetype;
        
        console.log(`[Submission] File saved locally: ${fileUrl}`);
    } else if (req.body.fileUrl) {
        fileUrl = req.body.fileUrl; 
    }

    // Check for existing submission
    let submission = await Submission.findOne({ taskId, studentId });

    if (submission) {
        console.log(`[Submission] Updating existing submission: ${submission.id}`);
        // Update existing
        if (fileUrl) submission.fileUrl = fileUrl;
        
        // Update metadata
        if (originalFileName) submission.originalFileName = originalFileName;
        if (fileSize) submission.fileSize = fileSize;
        if (fileType) submission.fileType = fileType;
        
        submission.submittedAt = Date.now();
        submission.status = 'SUBMITTED'; 
        submission.grade = null;
        submission.feedback = '';
        submission.gradedAt = undefined; // Reset gradedAt
        
        if (code) submission.code = code;
        if (language) submission.language = language;
        if (output) submission.output = output;
        
        // Clear GridFS ID if we are switching to local
        submission.fileId = null; 
        
        await submission.save();
        console.log(`[Submission] DB Update Successful for ID: ${submission.id}`);
        return res.status(200).json({ success: true, data: submission });
    }

    // Create new
    console.log("[Submission] Creating new submission document");
    submission = await Submission.create({
        taskId,
        studentId,
        studentName: studentName || req.user.name,
        fileUrl: fileUrl || '', 
        fileId: null, // Explicitly null for local storage
        originalFileName,
        fileSize,
        fileType,
        submittedAt: Date.now(),
        status: 'SUBMITTED',
        code,
        language,
        output
    });

    console.log(`[Submission] DB Create Successful for ID: ${submission.id}`);
    res.status(201).json({ success: true, data: submission });
  } catch (error) {
    console.error("[Submission] Create Error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Grade submission
// @route   PUT /api/submissions/:id/grade
// @access  Private (Instructor)
const gradeSubmission = async (req, res) => {
  try {
    const { grade, score, feedback } = req.body;
    const finalGrade = grade !== undefined ? grade : score;
    const submissionId = req.params.id;

    if (finalGrade === undefined) {
        return res.status(400).json({ success: false, message: 'Grade/Score is required' });
    }

    console.log(`[Grade] Grading submission ${submissionId}`);

    // Use Submission model directly
    const submission = await Submission.findById(submissionId);

    if (!submission) {
        console.warn(`[Grade] Submission not found: ${submissionId}`);
        return res.status(404).json({ success: false, message: 'Submission not found' });
    }

    submission.grade = finalGrade;
    submission.feedback = feedback || '';
    submission.status = 'GRADED';
    submission.gradedAt = Date.now();
    
    await submission.save();
    
    console.log(`[Grade] Saved successfully for submission ${submission.id}`);
    
    res.status(200).json({ success: true, data: submission });

  } catch (error) {
    console.error("[Grade] Error:", error);
    res.status(500).json({ success: false, message: error.message });
  }
};

// @desc    Download submission file
// @route   GET /api/submissions/:id/download
// @access  Private (Instructor)
const downloadSubmission = async (req, res) => {
    try {
        const submissionId = req.params.id;
        
        // Use Submission model directly
        const submission = await Submission.findById(submissionId);
        
        if (!submission) {
             return res.status(404).json({ success: false, message: 'Submission not found' });
        }
        
        console.log(`[Download] Request for submission ${submission.id}`);

        if (submission.fileUrl) {
             const absoluteFilePath = path.join(process.cwd(), 'uploads', submission.fileUrl);

             console.log(`[Download] Checking local file: ${absoluteFilePath}`);

             if (fs.existsSync(absoluteFilePath)) {
                 const filename = submission.originalFileName || path.basename(submission.fileUrl);
                 
                 res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
                 res.setHeader('Content-Type', submission.fileType || 'application/octet-stream');
                 
                 res.download(absoluteFilePath, filename, (err) => {
                     if (err) {
                         console.error("[Download] Send File Error:", err);
                         if (!res.headersSent) res.status(500).send("Could not download file");
                     }
                 });
                 return;
             }
        }
        
        return res.status(404).json({ success: false, message: 'File not found on server' });

    } catch (error) {
        console.error("[Download] Critical Error:", error);
        res.status(500).json({ success: false, message: 'Download failed' });
    }
};

export {
  getSubmissions,
  createSubmission,
  gradeSubmission,
  downloadSubmission
};
